language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - docker network create OMS
    - travis_retry docker-compose up -d
    - sleep 60
    - docker-compose logs


script:
    - docker-compose exec -T -d oms-legacy true 2>/dev/null || exit 1
