language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - docker network create OMS
    - travis_retry docker-compose up -d
    - sleep 60
    - docker-compose logs


script:
    - sudo docker-compose run -T oms-legacy ./vendor/bin/phpunit
