version: "3.2"

services:

### OMS-LEGACY        #######################################

    oms-legacy:
        build:
          context: ./$PATH_OMS_LEGACY/oms-legacy/
          dockerfile: ./Dockerfile.dev
        image: aegee/oms-legacy:dev
        restart: always
        volumes:
            - type: bind
              source: ./$PATH_OMS_LEGACY/../src/
              target: /usr/app/src
            - type: bind
              source: ./$PATH_OMS_LEGACY/../logs/
              target: /usr/app/logs
        labels:
          - "traefik.backend=oms-legacy"
          - "traefik.port=80"
          - "traefik.enable=true"
          - "registry.categories=(users, 10);(antennae, 10)"
          - "registry.backend=/api"
          - "registry.description=The legacy service, providing support for legacy systems"
networks:
  default:
    external:
      name: OMS
